jhiSort directive properties Error
jhiSort directive properties (ascending and callback)
```
[(ascending)]="ascending" [callback]="loadPage.bind(this)"
```
<br>
Errors<br>
````
error TS2339: Property 'translate' does not exist on type 'ProductComponent'
````
```
error TS2339: Property 'reverse' does not exist on type 'ProductComponent'
```